- name: Install deb package for elixir
  apt:
    deb: https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb

- name: apt update
  apt:
    update_cache: yes

- name: apt install elixir
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - esl-erlang
    - elixir
